# Lista de configuraci칩n por defecto
defaults:
  - dataset: dataset
  - reducer: pca
  - model: rf
  - experiment: base
  - override hydra/sweeper: basic

# Par치metros comunes a todos los experimentos
base:
  seed: 42
  test_size: 0.2

# Configuraci칩n del barrido (sweep)
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      experiment.seed: 42, 52, 30, 25, 38
      model: mlp, rf, svm, xgb
      reducer: kpca, pca, umap, ae
      reducer.params.n_components: 2, 4, 8, 16, 32, 64, 128, 256


# Configuraci칩n de MLflow
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "Clasificadores_por_defecto"

#todo lo que no sea modificado por swwep se hereda de base
